language: python
python:
  - "2.7"
  - "3.2"
# allow python dependencies to be installed via apt-get
virtualenv:
  system_site_packages: true
# setup system for GUI testing
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
# command to install dependencies
install:
  - pip install --upgrade pip
  - sudo apt-get update
  - sudo apt-get install -qq ibus python3-gi gir1.2-ibus-1.0 gir1.2-wnck-3.0 python-cairo pylint
  - "pip install -r requirements.txt"
  - pip install coveralls
# command to run tests
script:
  - nosetests  --with-coverage --cover-package=jekyll_helper
# run coveralls
after_success:
  - coveralls
